[package]
name = "ghtraffic"
version = "0.1.0"
edition = "2021"

[lib]
name = "ghtraffic"
path = "src/lib.rs"

[[bin]]
name = "render_website"
path = "src/bins/render_website.rs"

[dependencies]
lambda_http = "0.11.1"
tokio = { version = "1", features = ["macros"] }
