[package]
name = "ghtraffic"
version = "0.1.0"
edition = "2021"

[lib]
name = "ghtraffic"
path = "src/lib.rs"

[[bin]]
name = "render_website"
path = "src/bins/render_website.rs"

[dependencies]
anyhow = "1.0.86"
lambda_http = "0.11.1"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
thiserror = "1.0.61"
tokio = { version = "1", features = ["macros"] }
