[package]
name = "awe"
version = "0.1.0"
edition = "2021"

[lib]
name = "awe"
path = "src/lib.rs"

[[bin]]
name = "hello_world"
path = "src/bins/hello_world.rs"

[dependencies]
lambda_http = "0.11.1"
tokio = { version = "1", features = ["macros"] }
