name: CD

on:
    push:
        branches:
        - main
        paths:
        - 'infrastructure/**'
        - 'src/**'
        - 'scripts/**'
        - 'templates/**'
        - 'Cargo.toml'
        - '.github/workflows/cd.yml'

env:
    TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: opentofu/setup-opentofu@v1
          with:
            tofu_version: 1.6.0
            tofu_wrapper: false
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
        - name: Configure sccache env var and set build profile to ephemeral build
          run: |
            echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
            echo “SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
            echo “RUSTFLAGS=’--cfg profile=ephemeral-build’” >> $GITHUB_ENV
        - name: Run sccache-cache
          uses: mozilla-actions/sccache-action@v0.0.2
        - name: Build Lambda functions
          run: python3 ./scripts/build.py
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: "eu-west-1"
        - name: Init Tofu
          run: tofu -chdir=infrastructure init
        - name: Plan Tofu
          env:
              TF_VAR_GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
          run: tofu -chdir=infrastructure plan
        - name: Apply Tofu
          env:
              TF_VAR_GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
          run: tofu -chdir=infrastructure apply -auto-approve
